### ISSUE TITLE
Can the repo get a Makefile?

### ISSUE THREAD

**Issue by seankross** [getwilds/getwilds.github.io#4]
For those of us who are bad at Quarto but good at Make (perhaps this is only me)

**Comment by sckott** [comment]
yep! love me some make

**Comment by sckott** [comment]
@seankross can you test it out? its on main branch

**Comment by sckott** [comment]
i fiddled with checking if quarto installed first, but you get an error anyway if its not installed - not pretty but its there ish

**Comment by seankross** [comment]
This is great, thanks Scott.

**Comment by sckott** [comment]
@seankross readme added
